name: CI

env:
  NODE_VERSION: 14.17.3

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - uses: actions/checkout@v2

      - name: create a file
        run: echo ${{ github.sha }} > ./coverage/test

      - name: read contents of file
        run: cat ./coverage/test

      - name: jest coverage reporter
        uses: ./ # Uses an action in the root directory
        id: coverage-reporter
        with:
          branch-coverage-report-path: ./coverage/coverage-summary.json
          base-coverage-report-path: ./coverage/coverage-summary-master.json
          useSameComment: true